### ISSUE TITLE
adding citations to the algorithms

### ISSUE THREAD

**Issue by sertansenturk** [MTG/pycompmusic#8]
Since most of the analysis tools are developed as part of our research (e.g blob/master/compmusic/extractors/makam/pitch.py) and they are explained in their corresponding papers, do you think whether it's good to add the citation to the code? We can add it as part of the comments on the top, or/and as a variable named **citation**. 

I don't know the best conduct in these issues so I wanted to get a suggestion.

**Comment by sertansenturk** [comment]
Ok added it in the last two commits.

Before closing the issue: I am also writing the citation to the feature, so it's easy to remember the details after a long time. Please feel free to change this if you don't like how I'm doing or to remove if you don't like it at all.

**Comment by alastair** [comment]
One thing we need to make sure we're doing correctly:
pycompmusic is currently licensed as AGPL3. This means all the code for your extractors is too. Part of this is required because it uses essentia, which is also licensed the same.
Is this what we want to use for this extractor?  If there are other extractors that don't use essentia (matlab ones?) and we want to be licensed differently, we need to make sure we note this in the copyright notice at the top of the specific file.

**Comment by sankalpg** [comment]
Thanks Alastair for bringing this point in. So one thing is the actual code of our algorithms and the other is extractors which we write in pycompmusic. Those extractors are like wrapper functions which will use our core code (in the form of 'import module' or a binary.) Can we try to keep these two things separate? both in terms of the organization of the code and also interms of the licensing issues. Does that bring any benefit?

**Comment by alastair** [comment]
For essentia extractors, the AGPL doesn't give us any flexibility here. Because our wrappers link to essentia, which is AGPL, the wrapper must also be AGPL.
As we were discussing, if you have python source in an external module that we import, or we call a binary, we don't have this condition. The external can be any license, even closed, and we can keep the wrapper agpl.
Because it's a compmusic related project, pycompmusic should be primarily agpl licensed. 
The only exception should be non-essentia modules which we keep within the source tree, if the author/copyright holder has that preference.

**Comment by sankalpg** [comment]
Ok cool, its clear to me now. Thanks for explaining.

**Comment by sertansenturk** [comment]
@alastair Related to your question, as you stated this extractor should be licensed as AGPL3 since it uses essentia.

Regarding other algorithms I can only think of two examples now. The first MTG/makam-symbolic-phrase-segmentation/ is in AGPL3 and uses miditoolbox which is licensed as GPL2 (https://github.com/MTG/makam-symbolic-phrase-segmentation/blob/master/functions/external/miditoolbox/License.txt). The other is my audio-score alignment code, which is currently closed. We can decide how to license it when we get to the integration stage.

**Comment by alastair** [comment]
There may be some AGPL/GPL2 compatibility issues: https://www.gnu.org/philosophy/license-list.html#AGPL
We will have to look into it in further detail.

**Comment by sertansenturk** [comment]
I am not sure if there is any update on this issue. However I'm going to compile a master repository ("makam analysis toolbox") and start putting the citations there in the documentation. Therefore this is not an issue in pycompmusic on my side anymore.

**Comment by alastair** [comment]
I think we slowly came to the decision to make pycompmusic just a series of wrappers to the actual code. In that case, I think you're right and the citations should be listed in the projects that implement the code

**Comment by sertansenturk** [comment]
At least for my code I have moved everython to the headers. should we close the issue?

**Comment by georgid** [comment]
I have also the citation in the headers. Thanks

**Comment by sertansenturk** [comment]
It seems we forgot to close this issue. :)
